# k8app configuration for sentry-game-engine
# Python/Tornado game logic service

appName: sentry-game-engine
version: "1.0.0"

serviceAccountName: default

image:
  repository: registry.gitlab.com/gitops-poc-dzha/services/sentry-demo/game-engine
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: regsecret

# Service configuration (k8app format)
service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      externalPort: 8082
      internalPort: 8082
      protocol: TCP

# Health checks
livenessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8082
    path: "/health"
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8082
    path: "/health"
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Environment via configmap (environment-agnostic)
configmap:
  APP_VERSION: "1.0.0"
  # Enable Clean Architecture with Connect protocol support
  USE_CLEAN_ARCH: "true"
  # REDIS_URL is auto-injected by k8app when cache.enabled=true
  # Sentry configuration (DSN is universal, environment in overlay)
  SENTRY_DSN: "https://247f3c03b8bd3cca5851b3ef8bc9a437@o4509537604993024.ingest.de.sentry.io/4509848249499728"
  SENTRY_DEBUG: "false"
  SENTRY_PROFILES_SAMPLE_RATE: "0"
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  # Wager service integration (same namespace = short DNS)
  USE_WAGER_SERVICE: "true"
  WAGER_SERVICE_URL: "http://sentry-wager-sv:8085"
  # MONGODB_URL, RABBITMQ_URL, SENTRY_ENVIRONMENT → defined in env overlay

# =============================================================================
# Prometheus ServiceMonitor (k8app v3.8.0+)
# =============================================================================
serviceMonitor:
  enabled: true
  port: "http"
  path: "/metrics"
  interval: 30s

# In-Memory Cache (Redis) - k8app v3.8.0+
# Creates dedicated Redis instance for this service
cache:
  enabled: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  maxmemory: "200mb"
  maxmemoryPolicy: "allkeys-lru"
  exporter:
    enabled: true
    serviceMonitor:
      enabled: true

# Vault secrets integration (role/path in env overlay)
vault:
  enabled: true
