# k8app configuration for sentry-payment
# Node.js/Express payment service

appName: sentry-payment
version: "1.0.0"

serviceAccountName: default

image:
  repository: registry.gitlab.com/gitops-poc-dzha/sentry-demo/payment-service
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: regsecret

# Service configuration (k8app format)
service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      externalPort: 8083
      internalPort: 8083
      protocol: TCP

# Health checks
livenessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8083
    path: "/health"
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8083
    path: "/health"
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

# Environment via configmap (environment-agnostic)
configmap:
  APP_VERSION: "1.0.0"
  # Enable Connect protocol (in addition to REST)
  ENABLE_CONNECT: "true"
  ENABLE_REST: "true"
  # REDIS_URL is auto-injected by k8app when cache.enabled=true
  # Sentry configuration (DSN is universal, environment in overlay)
  SENTRY_DSN: "https://79d78d9950ba202dbd98e8b597d1a6e0@o4509616118562816.ingest.de.sentry.io/4509616251732048"
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  # MONGODB_URL, RABBITMQ_URL, SENTRY_ENVIRONMENT → defined in env overlay

# In-Memory Cache (Redis) - k8app v3.8.0+
# Creates dedicated Redis instance for this service
cache:
  enabled: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  maxmemory: "100mb"
  maxmemoryPolicy: "allkeys-lru"
  exporter:
    enabled: true
    serviceMonitor:
      enabled: true

# =============================================================================
# Prometheus ServiceMonitor (k8app v3.8.0+)
# =============================================================================
serviceMonitor:
  enabled: true
  port: "http"
  path: "/metrics"
  interval: 30s

# Vault secrets integration (role/path in env overlay)
vault:
  enabled: true
