# Dev environment overrides for sentry-payment

image:
  repository: registry.gitlab.com/gitops-poc-dzha/services/sentry-demo/payment-service
  tag: 88010cb6
replicaCount: 1
# Environment-specific configmap values
configmap:
  # Infrastructure (cross-namespace = FQDN)
  MONGODB_URL: "mongodb://mongodb.infra-dev.svc:27017/payments"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.infra-dev.svc:5672"
  # Environment indicator
  SENTRY_ENVIRONMENT: "dev"
# Vault (environment-specific)
vault:
  role: sentry-payment-dev
  path: gitops-poc-dzha/sentry-payment/dev/config
