# VaultStaticSecret for web-grpc
# This file should be applied after Vault is configured
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: web-grpc-auth
  namespace: web-grpc-dev  # Change per environment
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: web-grpc-dev  # Change per environment
    serviceAccount: web-grpc
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: web-grpc-secrets
  namespace: web-grpc-dev  # Change per environment
  labels:
    app.kubernetes.io/name: web-grpc
    app.kubernetes.io/part-of: gitops-poc
spec:
  type: kv-v2
  mount: secret
  path: gitops-poc/web-grpc/dev/config  # Change 'dev' per environment
  destination:
    name: web-grpc-secrets
    create: true
  refreshAfter: 1h
  vaultAuthRef: web-grpc-auth
