# VaultStaticSecret for web-grpc
# This file should be applied after Vault is configured
# Namespace scheme: poc-{env} (e.g., poc-dev, poc-staging, poc-prod)
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: web-grpc-auth
  namespace: poc-dev  # Change to poc-staging or poc-prod per environment
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: web-grpc-dev  # Change to web-grpc-staging or web-grpc-prod
    serviceAccount: web-grpc
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: web-grpc-secrets
  namespace: poc-dev  # Change to poc-staging or poc-prod per environment
  labels:
    app.kubernetes.io/name: web-grpc
    app.kubernetes.io/part-of: gitops-poc-dzha
spec:
  type: kv-v2
  mount: secret
  path: gitops-poc-dzha/web-grpc/dev/config  # Change 'dev' per environment
  destination:
    name: web-grpc-secrets
    create: true
  refreshAfter: 1h
  vaultAuthRef: web-grpc-auth
