# Web HTTP Backend - Default Values
# Uses nicholasjackson/fake-service for testing
# Based on k8app/app chart v3.4.0: https://github.com/d7561985/k8app

appName: web-http
version: "v0.19.1"

# Service Account (use default, k8app doesn't create SA)
serviceAccountName: default

# Image configuration (public image - no registry secret needed)
image:
  repository: nicholasjackson/fake-service
  tag: v0.19.1
  pullPolicy: IfNotPresent

# No imagePullSecrets needed - public image

# Service configuration (k8app format)
service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      externalPort: 9092
      internalPort: 9092
      protocol: TCP

# Health checks (k8app format)
livenessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 9092
    path: "/health"
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 9092
    path: "/ready"
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

# fake-service configuration via configmap
configmap:
  LISTEN_ADDR: "0.0.0.0:9092"
  SERVER_TYPE: "http"
  NAME: "web-http"
  MESSAGE: "Hello from HTTP backend"
