# Web HTTP Backend - Default Values
# Uses mendhak/http-https-echo for debugging request headers
# Based on k8app/app chart v3.4.0: https://github.com/d7561985/k8app

appName: web-http
version: "latest"

# Service Account (use default, k8app doesn't create SA)
serviceAccountName: default

# Image configuration
image:
  repository: mendhak/http-https-echo
  tag: latest
  pullPolicy: IfNotPresent

# Image Pull Secrets for GitLab Registry
imagePullSecrets:
  - name: regsecret

# Service configuration (k8app format)
# mendhak/http-https-echo listens on port 8080 (HTTP) and 8443 (HTTPS) by default
service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      externalPort: 9092
      internalPort: 8080
      protocol: TCP

# Health checks (k8app format)
# mendhak/http-https-echo responds on any path
livenessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8080
    path: "/health"
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8080
    path: "/ready"
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

# mendhak/http-https-echo configuration via configmap
configmap:
  HTTP_PORT: "8080"
  HTTPS_PORT: "8443"
  PRESERVE_HEADER_CASE: "true"
