# Web HTTP - Dev Environment
# Inherits from default.yaml

environment: dev
branch: main
replicas: 2
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
# Environment-specific overrides (k8app configmap format)
configmap:
  NAME: "web-http-dev"
  MESSAGE: "Hello from HTTP backend (DEV)"
  LOG_LEVEL: "debug"
labels:
  app.kubernetes.io/instance: web-http-dev
  environment: dev
annotations:
  argocd.argoproj.io/sync-wave: "0"
image:
  tag: 457b2e2b
  repository: registry.gitlab.com/gitops-poc-dzha/services/web-http
