# Web HTTP - Dev Environment

environment: dev
branch: main
replicas: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

env:
  - name: LISTEN_ADDR
    value: "0.0.0.0:9092"
  - name: SERVER_TYPE
    value: "http"
  - name: NAME
    value: "web-http-dev"
  - name: MESSAGE
    value: "Hello from HTTP backend (DEV)"
  - name: LOG_LEVEL
    value: "debug"

labels:
  app.kubernetes.io/instance: web-http-dev
  environment: dev

annotations:
  argocd.argoproj.io/sync-wave: "0"
