# Web HTTP - Production Environment

environment: prod
branch: main
replicas: 3

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: LISTEN_ADDR
    value: "0.0.0.0:9092"
  - name: SERVER_TYPE
    value: "http"
  - name: NAME
    value: "web-http-prod"
  - name: MESSAGE
    value: "Hello from HTTP backend (PROD)"

labels:
  app.kubernetes.io/instance: web-http-prod
  environment: prod

annotations:
  argocd.argoproj.io/sync-wave: "0"

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 2
