# Web HTTP - Staging Environment
# Inherits from default.yaml

environment: staging
branch: main
replicas: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Environment-specific overrides (k8app configmap format)
configmap:
  NAME: "web-http-staging"
  MESSAGE: "Hello from HTTP backend (STAGING)"

labels:
  app.kubernetes.io/instance: web-http-staging
  environment: staging

annotations:
  argocd.argoproj.io/sync-wave: "0"
