# =============================================================================
# Platform Core - Environment & Services Configuration
# =============================================================================
# Core infrastructure for application deployment.
# =============================================================================

# Namespaces
namespaces:
  enabled: true
  labels:
    app.kubernetes.io/managed-by: platform-core

# Gateway for environments
gateway:
  enabled: true
  gatewayClassName: cilium
  listener:
    name: http-app
    protocol: HTTP
    port: 80
  certManager:
    enabled: false

# Domain mirrors
domainMirrors:
  enabled: true
  addToGateway: true
  createDNS: true
  addToTunnel: true
  defaultRoutes:
    - name: api
      path: /api
      pathType: PathPrefix
      serviceName: api-gateway-sv
      servicePort: 8080
    - name: frontend
      path: /
      pathType: PathPrefix
      serviceName: sentry-frontend-sv
      servicePort: 4200

# Services Registry
services:
  api-gateway:
    syncWave: "0"

  web-grpc:
    syncWave: "0"

  web-http:
    syncWave: "0"

  health-demo:
    syncWave: "0"

  user-service:
    syncWave: "0"
    repoURL: https://gitlab.com/gitops-poc-dzha/services/user-service.git
    path: .cicd

  sentry-frontend:
    syncWave: "1"
    repoURL: https://gitlab.com/gitops-poc-dzha/services/sentry-demo.git
    path: frontend/.cicd

  sentry-game-engine:
    syncWave: "0"
    repoURL: https://gitlab.com/gitops-poc-dzha/services/sentry-demo.git
    path: game-engine/.cicd

  sentry-payment:
    syncWave: "0"
    repoURL: https://gitlab.com/gitops-poc-dzha/services/sentry-demo.git
    path: payment-service/.cicd

  sentry-wager:
    syncWave: "0"
    repoURL: https://gitlab.com/gitops-poc-dzha/services/sentry-demo.git
    path: wager-service/.cicd

  analytics-service:
    syncWave: "0"
    repoURL: https://gitlab.com/gitops-poc-dzha/services/analytics-service.git
    path: .cicd

# ApplicationSet for services
applicationSet:
  enabled: true
  name: gitops-services

# Bootstrap job for Vault
job:
  enabled: true
  image: hashicorp/vault:1.15
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  hook: PreSync
  hookDeletePolicy: HookSucceeded
  syncWave: "-10"
