# VaultStaticSecret for API Gateway
# This file should be applied after Vault is configured
# Source: https://developer.hashicorp.com/vault/docs/deploy/kubernetes/vso

# Note: Create one per environment by changing namespace and path
# Namespace scheme: poc-{env} (e.g., poc-dev, poc-staging, poc-prod)
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: api-gateway-auth
  namespace: poc-dev  # Change to poc-staging or poc-prod per environment
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: api-gateway-dev  # Change to api-gateway-staging or api-gateway-prod
    serviceAccount: api-gateway
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: api-gateway-secrets
  namespace: poc-dev  # Change to poc-staging or poc-prod per environment
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: gitops-poc-dzha
spec:
  type: kv-v2
  mount: secret
  path: gitops-poc-dzha/api-gateway/dev/config  # Change 'dev' per environment
  destination:
    name: api-gateway-secrets
    create: true
  refreshAfter: 1h
  vaultAuthRef: api-gateway-auth
