# VaultStaticSecret for API Gateway
# This file should be applied after Vault is configured
# Source: https://developer.hashicorp.com/vault/docs/deploy/kubernetes/vso

# Note: Create one per environment by changing namespace and path
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: api-gateway-auth
  namespace: api-gateway-dev  # Change per environment
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: api-gateway-dev  # Change per environment
    serviceAccount: api-gateway
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: api-gateway-secrets
  namespace: api-gateway-dev  # Change per environment
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: gitops-poc
spec:
  type: kv-v2
  mount: secret
  path: gitops-poc/api-gateway/dev/config  # Change 'dev' per environment
  destination:
    name: api-gateway-secrets
    create: true
  refreshAfter: 1h
  vaultAuthRef: api-gateway-auth
