# API Gateway - Default Values (inherited by all environments)
# Based on k8app/app chart: https://github.com/d7561985/k8app
# Envoy Proxy with Go config generator

appName: api-gateway
version: "1.0.0"

# Service Account
serviceAccountName: api-gateway

# Image configuration
# For local Minikube: repository: api-gateway, tag: local, pullPolicy: Never
# For GitLab Registry: repository: registry.gitlab.com/${GITLAB_GROUP}/api-gateway
image:
  repository: api-gateway
  tag: local
  pullPolicy: Never  # Change to IfNotPresent for GitLab Registry

# Service configuration (k8app format)
service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      externalPort: 8080
      internalPort: 8080
      protocol: TCP
    admin:
      externalPort: 8000
      internalPort: 8000
      protocol: TCP

# Health checks - Envoy admin endpoint (k8app format)
livenessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8000
    path: "/ready"
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8000
    path: "/ready"
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

# Environment variables via configmap (injected via envFrom)
configmap:
  LOG_LEVEL: "info"
  AUTH_ADAPTER_HOST: "auth-adapter"
  OPEN_TELEMETRY_HOST: "127.0.0.1"
  OPEN_TELEMETRY_PORT: "4317"

# ConfigFiles for gateway config (mounted to specified path)
configfiles:
  mountPath: "/opt/auth-adapter"
  data:
    config.yaml: |
      api_route: /api/

      clusters:
        - name: web
          addr: "web-grpc:9091"
          type: "grpc"
        - name: web-http
          addr: "web-http:9092"
          type: "http"
          health_check:
            path: "/health"
            interval_seconds: 10
        - name: health-demo
          addr: "health-demo:8081"
          type: "grpc"

      apis:
        - name: FakeService
          cluster: web
          auth: {policy: no-need}
          methods:
            - name: Handle
              auth: {policy: no-need}
        - name: HttpService
          cluster: web-http
          auth: {policy: no-need}
          methods:
            - name: health
              auth: {policy: no-need}
            - name: echo
              auth: {policy: no-need}
        - name: grpc.health.v1.Health
          cluster: health-demo
          auth: {policy: no-need}
          methods:
            - name: Check
              auth: {policy: no-need}
