# API Gateway - Default Values (inherited by all environments)
# Based on k8app/app chart: https://github.com/d7561985/k8app

appName: api-gateway
version: "1.0.0"

# Service Account
serviceAccountName: api-gateway

# Image configuration
# For local Minikube: repository: api-gateway, tag: local, pullPolicy: Never
# For GitLab Registry: repository: registry.gitlab.com/${GITLAB_GROUP}/api-gateway
image:
  repository: api-gateway
  tag: local
  pullPolicy: Never  # Change to IfNotPresent for GitLab Registry

# Enable imagePullSecrets for GitLab Container Registry
# k8app chart uses hardcoded secret name "regsecret"
# Run: ./scripts/setup-registry-secret.sh to create the secret
deploySecretHarbor: false  # Set to true when using GitLab Registry

# Container ports
containerPort: 8080

# Additional ports (admin interface)
additionalPorts:
  - name: admin
    containerPort: 8000
    protocol: TCP

# Service configuration
service:
  enabled: true
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: admin
      port: 8000
      targetPort: 8000

# Health checks
livenessProbe:
  enabled: true
  httpGet:
    path: /ready
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /ready
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5

# Environment variables (common)
env:
  - name: OPEN_TELEMETRY_ENABLE
    value: "false"
  - name: AUTH_ADAPTER_HOST
    value: "auth-adapter"  # Same namespace, short DNS name works

# ConfigMap for gateway config
configmap:
  enabled: true
  data:
    config.yaml: |
      # Gateway configuration will be mounted here

# Labels (required by policy)
labels:
  app.kubernetes.io/name: api-gateway
  app.kubernetes.io/component: gateway
  app.kubernetes.io/part-of: gitops-poc-dzha
  app.kubernetes.io/managed-by: helm
