# API Gateway - Default Values (inherited by all environments)
# Based on k8app/app chart v3.5.1: https://github.com/d7561985/k8app
# Envoy Proxy with Go config generator + auth-adapter sidecar

appName: api-gateway
version: "1.0.0"

# Service Account (use default, k8app doesn't create SA)
serviceAccountName: default

# Image configuration
# For local Minikube: repository: api-gateway, tag: local, pullPolicy: Never
# For GitLab Registry: repository: registry.gitlab.com/${GITLAB_GROUP}/api-gateway
image:
  repository: api-gateway
  tag: local
  pullPolicy: Never  # Change to IfNotPresent for GitLab Registry

# Image Pull Secrets - universal format (k8app v3.4.0+)
imagePullSecrets:
  - name: regsecret

# Service configuration (k8app format)
service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      externalPort: 8080
      internalPort: 8080
      protocol: TCP
    admin:
      externalPort: 8000
      internalPort: 8000
      protocol: TCP

# Health checks - Envoy admin endpoint (k8app format)
livenessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8000
    path: "/ready"
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8000
    path: "/ready"
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

# Environment variables via configmap (injected via envFrom)
configmap:
  LOG_LEVEL: "info"
  AUTH_ADAPTER_HOST: "127.0.0.1"  # Sidecar via localhost
  OPEN_TELEMETRY_HOST: "127.0.0.1"
  OPEN_TELEMETRY_PORT: "4317"

# =============================================================================
# Secrets Configuration (k8app v3.4.0+)
# =============================================================================
secrets:
  API_KEY: "/gitops-poc-dzha/api-gateway/dev/config"

# Secrets Provider Configuration (k8app v3.4.0+)
secretsProvider:
  provider: "vault"
  vault:
    authRef: "vault-auth"
    mount: "secret"
    type: "kv-v2"
    refreshAfter: "1h"

# =============================================================================
# Shared Volumes (k8app v3.5.0+)
# =============================================================================
# config.yaml is in Docker image at /opt/auth-adapter/config.yaml
# initContainer copies it to emptyDir, which is mounted to both containers
sharedVolumes:
  auth-config:
    type: emptyDir
    mountPath: "/opt/auth-adapter"

# =============================================================================
# Init Container (k8app v3.5.0+)
# =============================================================================
# Uses main image (api-gateway) to copy config from /opt/config-source to shared volume
initContainers:
  command:
    - sh
    - -c
  args:
    - cp /opt/config-source/config.yaml /opt/auth-adapter/config.yaml

# =============================================================================
# Auth-Adapter Sidecar (k8app v3.5.0+ extensions)
# =============================================================================
extensions:
  auth-adapter:
    image:
      repository: auth-adapter
      tag: 7306e90b
    command:
      - /app/auth-adapter
    env:
      OTEL_SERVICE_NAME: "auth-adapter"
    livenessProbe:
      tcpSocket:
        port: 9000
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      tcpSocket:
        port: 9000
      initialDelaySeconds: 5
      periodSeconds: 5
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

# =============================================================================
# Gateway API HTTPRoute (k8app v3.6.0+)
# =============================================================================
# Routes /api/* traffic from Gateway to api-gateway
# More specific path (/api) takes precedence over frontend's (/)
httpRoute:
  enabled: true
  parentRefs:
    - name: gateway
      namespace: poc-dev
      sectionName: http-app
  hostnames:
    - app.demo-poc-01.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: api-gateway-sv
          port: 8080
