# API Gateway - Dev Environment Overrides
# Inherits from default.yaml
# CI updates image.repository and image.tag on each build

environment: dev
branch: main
# Image - CI updates these values
image:
  repository: registry.gitlab.com/gitops-poc-dzha/api-gateway
  tag: cd8b76e2
  pullPolicy: IfNotPresent
# Replicas
replicas: 1
# Resources (minimal for dev)
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
# Environment-specific overrides (k8app configmap format)
configmap:
  LOG_LEVEL: "debug"
# Labels
labels:
  app.kubernetes.io/instance: api-gateway-dev
  environment: dev
# Annotations for ArgoCD
annotations:
  argocd.argoproj.io/sync-wave: "2" # Deploy after auth-adapter
# Auth-adapter sidecar - override image from GitLab registry
extensions:
  auth-adapter:
    image:
      repository: registry.gitlab.com/gitops-poc-dzha/auth-adapter
      tag: 7306e90b
      pullPolicy: IfNotPresent
# HTTPRoute (environment-specific)
httpRoute:
  parentRefs:
    - name: gateway
      namespace: poc-dev
      sectionName: http-app
  hostnames:
    - app.demo-poc-01.work
