# API Gateway - Production Environment Overrides
# Inherits from default.yaml
# CI updates image.repository and image.tag on each build

environment: prod
branch: main

# Image - CI updates these values
image:
  repository: registry.gitlab.com/gitops-poc-dzha/services/api-gateway
  tag: latest
  pullPolicy: IfNotPresent

# Replicas
replicas: 3

# Resources (production-grade)
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

# Environment-specific overrides (k8app configmap format)
configmap:
  OPEN_TELEMETRY_ENABLE: "true"
  LOG_LEVEL: "warn"

# Labels
labels:
  app.kubernetes.io/instance: api-gateway-prod
  environment: prod

# Annotations for ArgoCD
annotations:
  argocd.argoproj.io/sync-wave: "2"

# HPA for production
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

# PDB for high availability
pdb:
  enabled: true
  minAvailable: 2
