# API Gateway - Staging Environment Overrides
# Inherits from default.yaml
# CI updates image.repository and image.tag on each build

environment: staging
branch: main

# Image - CI updates these values
image:
  repository: registry.gitlab.com/gitops-poc-dzha/services/api-gateway
  tag: latest
  pullPolicy: IfNotPresent

# Replicas
replicas: 2

# Resources (moderate for staging)
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Environment-specific overrides (k8app configmap format)
configmap:
  OPEN_TELEMETRY_ENABLE: "true"
  LOG_LEVEL: "info"

# Labels
labels:
  app.kubernetes.io/instance: api-gateway-staging
  environment: staging

# Annotations for ArgoCD
annotations:
  argocd.argoproj.io/sync-wave: "2"

# HPA for staging
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

# =============================================================================
# Secrets Configuration (k8app v3.4.0+)
# =============================================================================
secrets:
  API_KEY: "/gitops-poc-dzha/api-gateway/staging/config"

extensions:
  auth-adapter:
    image:
      repository: registry.gitlab.com/gitops-poc-dzha/services/auth-adapter
      tag: v1.0.2
      pullPolicy: IfNotPresent
# HTTPRoute (environment-specific)
httpRoute:
  parentRefs:
    - name: gateway
      namespace: poc-staging
      sectionName: http-app
  hostnames:
    - stage.demo-poc-01.work