# Vault Secrets Configuration for {{SERVICE_NAME}}
# Apply this file after Vault is configured and service is deployed
#
# Create one per environment by changing:
#   - namespace: {{SERVICE_NAME}}-{env}
#   - role: {{SERVICE_NAME}}-{env}
#   - path: gitops-poc-dzha/{{SERVICE_NAME}}/{env}/config
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{SERVICE_NAME}}-auth
  namespace: {{SERVICE_NAME}}-dev  # Change per environment
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: {{SERVICE_NAME}}-dev  # Change per environment
    serviceAccount: {{SERVICE_NAME}}
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{SERVICE_NAME}}-secrets
  namespace: {{SERVICE_NAME}}-dev  # Change per environment
  labels:
    app.kubernetes.io/name: {{SERVICE_NAME}}
    app.kubernetes.io/part-of: gitops-poc-dzha
spec:
  type: kv-v2
  mount: secret
  path: gitops-poc-dzha/{{SERVICE_NAME}}/dev/config  # Change 'dev' per environment
  destination:
    name: {{SERVICE_NAME}}-secrets
    create: true
  refreshAfter: 1h
  vaultAuthRef: {{SERVICE_NAME}}-auth
