# =============================================================================
# Platform Base Configuration
# =============================================================================
# Shared values used by all platform charts.
# This file is referenced by ArgoCD multi-source Applications.
#
# Usage: Each chart combines base.yaml + chart-specific.yaml
# =============================================================================

# -----------------------------------------------------------------------------
# Global Settings
# -----------------------------------------------------------------------------
global:
  gitlabGroup: gitops-poc-dzha
  vaultPathPrefix: gitops-poc-dzha
  namespacePrefix: poc
  k8app:
    repoURL: https://d7561985.github.io/k8app
    chart: app
    version: "3.8.0"

# -----------------------------------------------------------------------------
# Environments
# -----------------------------------------------------------------------------
environments:
  dev:
    enabled: true
    autoSync: true
    domain: "app.demo-poc-01.work"
    infraNamespace: "infra-dev"
    mirrors:
      - domain: "demo-poc-02.work"
        zoneId: "76d0dce2fd263121a17a36a188081b99"

# -----------------------------------------------------------------------------
# Vault Configuration
# -----------------------------------------------------------------------------
vault:
  address: "http://vault.vault.svc:8200"
  mount: "secret"
  tokenSecret:
    name: vault-admin-token
    key: token

# -----------------------------------------------------------------------------
# VaultAuth Configuration
# -----------------------------------------------------------------------------
vaultAuth:
  enabled: true
  audiences:
    - vault

# -----------------------------------------------------------------------------
# ArgoCD ApplicationSet Configuration
# -----------------------------------------------------------------------------
applicationSet:
  project: gitops-poc-dzha

# -----------------------------------------------------------------------------
# DNS Management (external-dns)
# -----------------------------------------------------------------------------
dns:
  enabled: true
  provider: cloudflare
  cloudflare:
    proxied: true
    secretName: cloudflare-api-credentials
    namespace: external-dns

# -----------------------------------------------------------------------------
# Ingress Provider Configuration
# -----------------------------------------------------------------------------
ingress:
  provider: cloudflare-tunnel
  cloudflare:
    enabled: true
    tunnelId: "1172317a-8885-492f-9744-dfba842c4d88"
    credentialsSecret: cloudflared-credentials
    replicas: 2
    namespace: cloudflare
