apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: infra-dev
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  namespaceSelector:
    matchNames:
      - infra-dev
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
