# Auth Adapter - Default Values (inherited by all environments)
# Based on k8app/app chart: https://github.com/d7561985/k8app
# gRPC ext_authz service for Envoy

appName: auth-adapter
version: "1.0.0"

# Service Account
serviceAccountName: auth-adapter

# Image configuration
# For local Minikube: repository: auth-adapter, tag: local, pullPolicy: Never
# For GitLab Registry: repository: registry.gitlab.com/${GITLAB_GROUP}/auth-adapter
image:
  repository: auth-adapter
  tag: local
  pullPolicy: Never  # Change to IfNotPresent for GitLab Registry

# Service configuration (k8app format)
service:
  enabled: true
  type: ClusterIP
  ports:
    grpc:
      externalPort: 9000
      internalPort: 9000
      protocol: TCP

# Health checks - gRPC health check (k8app format)
# Note: k8app may not support grpc probes natively, using tcpSocket as fallback
livenessProbe:
  enabled: true
  mode: tcpSocket
  tcpSocket:
    port: 9000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: tcpSocket
  tcpSocket:
    port: 9000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

# Environment variables via configmap
configmap:
  OTEL_SERVICE_NAME: "auth-adapter"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  AUTH_SERVICE_ADDR: ""
  RECAPTCHA_URL: ""

# ConfigFiles for auth config (mounted to /opt/auth-adapter)
configfiles:
  mountPath: "/opt/auth-adapter"
  data:
    config.yaml: |
      apis:
        - name: FakeService
          auth: {policy: no-need}
          methods:
            - name: Handle
              auth: {policy: no-need}
        - name: HttpService
          auth: {policy: no-need}
          methods:
            - name: health
              auth: {policy: no-need}
            - name: echo
              auth: {policy: no-need}
        - name: grpc.health.v1.Health
          auth: {policy: no-need}
          methods:
            - name: Check
              auth: {policy: no-need}
