# Auth Adapter - Production Environment Overrides

environment: prod
branch: main
replicas: 3

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: OTEL_ENABLE
    value: "true"
  - name: LOG_LEVEL
    value: "warn"

labels:
  app.kubernetes.io/instance: auth-adapter-prod
  environment: prod

annotations:
  argocd.argoproj.io/sync-wave: "1"

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 2
