# Auth Adapter - Staging Environment Overrides
# Inherits from default.yaml
# CI updates image.repository and image.tag on each build

environment: staging
branch: main

# Image - CI updates these values
image:
  repository: registry.gitlab.com/gitops-poc-dzha/auth-adapter
  tag: latest
  pullPolicy: IfNotPresent

replicas: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Environment-specific overrides (k8app configmap format)
configmap:
  OTEL_ENABLE: "true"
  LOG_LEVEL: "info"

labels:
  app.kubernetes.io/instance: auth-adapter-staging
  environment: staging

annotations:
  argocd.argoproj.io/sync-wave: "1"
