# =============================================================================
# {{SERVICE_NAME}} - Default Values (k8app chart v3.8.0+)
# =============================================================================
# Base configuration shared across all environments
# Docs: https://github.com/d7561985/k8app
#
# Replace: {{SERVICE_NAME}} with your service name
# =============================================================================

appName: {{SERVICE_NAME}}
version: "1.0.0"

# Service Account (use default, k8app doesn't create SA)
serviceAccountName: default

# =============================================================================
# Image Configuration
# =============================================================================
image:
  repository: {{SERVICE_NAME}}
  tag: local
  pullPolicy: Never  # IfNotPresent for GitLab Registry

imagePullSecrets:
  - name: regsecret

# =============================================================================
# Service Configuration
# =============================================================================
service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      externalPort: 8080
      internalPort: 8080
      protocol: TCP
    # For gRPC services:
    # grpc:
    #   externalPort: 8081
    #   internalPort: 8081
    #   protocol: TCP
    metrics:
      externalPort: 9090
      internalPort: 9090
      protocol: TCP

# =============================================================================
# Health Checks
# =============================================================================
# HTTP endpoints:
livenessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8080
    path: "/health"
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8080
    path: "/ready"
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

# For gRPC services use tcpSocket:
# livenessProbe:
#   enabled: true
#   mode: tcpSocket
#   tcpSocket:
#     port: 8081
#   initialDelaySeconds: 10
#   periodSeconds: 10

# =============================================================================
# Command Line Arguments (optional)
# =============================================================================
# args:
#   - "-port=8080"
#   - "-metrics-port=9090"

# =============================================================================
# Environment via ConfigMap
# =============================================================================
# configmap:
#   LOG_LEVEL: "info"
#   DATABASE_HOST: "mongodb.infra-dev.svc.cluster.local"

# =============================================================================
# Secrets from Vault (k8app v3.4.0+)
# =============================================================================
# Format: ENV_VAR_NAME: "vault-path"
# Absolute path (starts with /): /gitops-poc-dzha/{{SERVICE_NAME}}/dev/config
secrets: {}
  # DATABASE_PASSWORD: "/gitops-poc-dzha/{{SERVICE_NAME}}/dev/config"
  # API_KEY: "/gitops-poc-dzha/{{SERVICE_NAME}}/dev/config"

secretsProvider:
  provider: "vault"
  vault:
    authRef: "vault-auth"
    mount: "secret"
    type: "kv-v2"
    refreshAfter: "1h"

# =============================================================================
# Prometheus ServiceMonitor (k8app v3.8.0+)
# =============================================================================
serviceMonitor:
  enabled: true
  port: "metrics"
  path: "/metrics"
  interval: 30s

# =============================================================================
# Gateway API HTTPRoute (k8app v3.6.0+)
# =============================================================================
# httpRoute:
#   enabled: true
#   parentRefs:
#     - name: gateway
#       namespace: poc-dev
#       sectionName: http-app
#   hostnames:
#     - app.demo-poc-01.work
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /api/{{SERVICE_NAME}}
#       backendRefs:
#         - name: {{SERVICE_NAME}}-sv
#           port: 8080
