# Dev environment values for {{SERVICE_NAME}}
# Inherits from default.yaml
#
# Image tag is automatically updated by CI pipeline

# Environment identifier
environment: dev

# Image (updated by CI)
image:
  tag: "latest"  # CI will update this

# Replicas (minimal for dev)
replicaCount: 1

# Resources (minimal for dev)
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Environment variables
env:
  - name: ENVIRONMENT
    value: "dev"
  - name: LOG_LEVEL
    value: "debug"

# Labels
labels:
  app.kubernetes.io/instance: "{{SERVICE_NAME}}-dev"
  environment: "dev"
