# Staging environment values for {{SERVICE_NAME}}
# Inherits from default.yaml
#
# Image tag is automatically updated by CI pipeline (manual trigger)

# Environment identifier
environment: staging

# Image (updated by CI)
image:
  tag: "latest"  # CI will update this

# Replicas (moderate for staging)
replicaCount: 2

# Resources (moderate for staging)
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Environment variables
env:
  - name: ENVIRONMENT
    value: "staging"
  - name: LOG_LEVEL
    value: "info"

# Labels
labels:
  app.kubernetes.io/instance: "{{SERVICE_NAME}}-staging"
  environment: "staging"
