# Analytics Service - Default Values
# Inherits: serviceAccountName, imagePullSecrets, secretsProvider, serviceMonitor
# from platform shared/k8app-defaults.yaml

appName: analytics-service
version: "1.0.0"

image:
  repository: analytics-service
  tag: local
  pullPolicy: Never

service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      externalPort: 8081
      internalPort: 8081
      protocol: TCP
    metrics:
      externalPort: 9090
      internalPort: 9090
      protocol: TCP

livenessProbe:
  enabled: true
  mode: tcpSocket
  tcpSocket:
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: tcpSocket
  tcpSocket:
    port: 8081
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

args:
  - "-port=8081"
  - "-metrics-port=9090"

configmap:
  REDIS_ADDR: ""
