apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  # Monitor services in same namespace (set by ArgoCD destination)
  namespaceSelector:
    matchNames: []
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
