# User Service - Default Values
# Authentication and user management service
# Inherits: serviceAccountName, imagePullSecrets, secretsProvider, serviceMonitor
# from platform shared/k8app-defaults.yaml

appName: user-service
version: "1.0.0"

image:
  repository: user-service
  tag: local
  pullPolicy: Never

service:
  enabled: true
  type: ClusterIP
  ports:
    grpc:
      externalPort: 8081
      internalPort: 8081
      protocol: TCP
    metrics:
      externalPort: 9090
      internalPort: 9090
      protocol: TCP

livenessProbe:
  enabled: true
  mode: tcpSocket
  tcpSocket:
    port: 8081
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: tcpSocket
  tcpSocket:
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

args:
  - "-port=8081"
  - "-metrics-port=9090"

# Environment via configmap (infrastructure addresses in env overlay)
configmap:
  MONGODB_DATABASE: "users"

# Service-specific secrets (paths only, provider inherited)
secrets:
  JWT_SECRET: "/gitops-poc-dzha/user-service/dev/config"
