# Web gRPC Backend - Default Values
# Uses nicholasjackson/fake-service for testing
# Based on k8app/app chart: https://github.com/d7561985/k8app

appName: web-grpc
version: "v0.19.1"

serviceAccountName: web-grpc

# Image configuration (public image - no registry secret needed)
image:
  repository: nicholasjackson/fake-service
  tag: v0.19.1
  pullPolicy: IfNotPresent

# Service configuration (k8app format)
service:
  enabled: true
  type: ClusterIP
  ports:
    grpc:
      externalPort: 9091
      internalPort: 9091
      protocol: TCP

# Health checks (k8app format)
livenessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 9091
    path: "/health"
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 9091
    path: "/ready"
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

# fake-service configuration via configmap
configmap:
  LISTEN_ADDR: "0.0.0.0:9091"
  SERVER_TYPE: "grpc"
  NAME: "web-grpc"
  MESSAGE: "Hello from gRPC backend"
