# Web gRPC - Dev Environment
# Inherits from default.yaml

environment: dev
branch: main
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
# Environment-specific overrides (k8app configmap format)
configmap:
  NAME: "web-grpc-dev"
  MESSAGE: "Hello from gRPC backend (DEV)"
  LOG_LEVEL: "debug"
labels:
  app.kubernetes.io/instance: web-grpc-dev
  environment: dev
annotations:
  argocd.argoproj.io/sync-wave: "0" # Deploy first (no dependencies)
image:
  tag: fdf1dc3c
  repository: registry.gitlab.com/gitops-poc-dzha/web-grpc
