# Web gRPC - Production Environment
# Inherits from default.yaml

environment: prod
branch: main
replicas: 3

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Environment-specific overrides (k8app configmap format)
configmap:
  NAME: "web-grpc-prod"
  MESSAGE: "Hello from gRPC backend (PROD)"

labels:
  app.kubernetes.io/instance: web-grpc-prod
  environment: prod

annotations:
  argocd.argoproj.io/sync-wave: "0"

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 2
