#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
echo_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
echo_error() { echo -e "${RED}[ERROR]${NC} $1"; }
echo_header() { echo -e "\n${BLUE}=== $1 ===${NC}"; }

echo "========================================"
echo "  GitOps POC Project Initialization"
echo "========================================"

# Load .env if exists, otherwise use defaults
if [ -f "$ROOT_DIR/.env" ]; then
    echo_info "Loading configuration from .env"
    source "$ROOT_DIR/.env"
else
    echo_warn ".env file not found, using defaults"
    echo_info "Run: cp .env.example .env && vim .env"
fi

# Set defaults
GITLAB_GROUP="${GITLAB_GROUP:-gitops-poc}"
GITLAB_HOST="${GITLAB_HOST:-gitlab.com}"
PROJECT_PREFIX="${PROJECT_PREFIX:-}"
DOCKER_REGISTRY="${DOCKER_REGISTRY:-registry.gitlab.com/${GITLAB_GROUP}}"
KUBE_CONTEXT="${KUBE_CONTEXT:-${GITLAB_GROUP}/gitops-config:minikube-agent}"
VAULT_PATH_PREFIX="${VAULT_PATH_PREFIX:-gitops-poc}"
SERVICES="${SERVICES:-api-gateway auth-adapter web-grpc web-http health-demo}"
ENVIRONMENTS="${ENVIRONMENTS:-dev staging prod}"
NAMESPACE_PREFIX="${NAMESPACE_PREFIX:-poc}"

echo ""
echo "Configuration:"
echo "  GITLAB_GROUP:     $GITLAB_GROUP"
echo "  GITLAB_HOST:      $GITLAB_HOST"
echo "  DOCKER_REGISTRY:  $DOCKER_REGISTRY"
echo "  KUBE_CONTEXT:     $KUBE_CONTEXT"
echo "  VAULT_PATH:       $VAULT_PATH_PREFIX"
echo "  SERVICES:         $SERVICES"
echo "  ENVIRONMENTS:     $ENVIRONMENTS"
echo "  NAMESPACE_PREFIX: $NAMESPACE_PREFIX"
echo ""
echo "Namespaces will be: ${NAMESPACE_PREFIX}-dev, ${NAMESPACE_PREFIX}-staging, ${NAMESPACE_PREFIX}-prod"
echo ""

# Confirm
read -p "Continue with this configuration? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo_warn "Aborted. Edit .env and run again."
    exit 1
fi

echo_header "Updating ApplicationSet"

# Update applicationset.yaml
APPSET_FILE="$ROOT_DIR/gitops-config/argocd/applicationset.yaml"

# Build services list for ApplicationSet
SERVICES_YAML=""
for SERVICE in $SERVICES; do
    SERVICES_YAML="${SERVICES_YAML}                - service: ${SERVICE}
                  repoURL: https://${GITLAB_HOST}/${GITLAB_GROUP}/${SERVICE}.git
                  syncWave: \"0\"
"
done

# Create updated applicationset
cat > "$APPSET_FILE" << EOF
# ArgoCD ApplicationSet for Multi-Environment Deployment
# Auto-generated by init-project.sh
# GitLab Group: ${GITLAB_GROUP}

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ${GITLAB_GROUP}-services
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
${SERVICES_YAML}
          - list:
              elements:
                - env: dev
                  autoSync: "true"
                - env: staging
                  autoSync: "true"
                - env: prod
                  autoSync: "false"

  template:
    metadata:
      name: '{{service}}-{{env}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{service}}'
        environment: '{{env}}'
        app.kubernetes.io/part-of: ${GITLAB_GROUP}
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: ${GITLAB_GROUP}

      sources:
        - repoURL: https://d7561985.github.io/k8app
          chart: app
          targetRevision: '*'
          helm:
            valueFiles:
              - \$values/.cicd/default.yaml
              - \$values/.cicd/{{env}}.yaml

        - repoURL: '{{repoURL}}'
          targetRevision: main
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: '${NAMESPACE_PREFIX}-{{env}}'

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
          selfHeal: true

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas

      revisionHistoryLimit: 3
EOF

echo_info "Updated: $APPSET_FILE"

echo_header "Updating ArgoCD Project"

# Update project.yaml
PROJECT_FILE="$ROOT_DIR/gitops-config/argocd/project.yaml"

cat > "$PROJECT_FILE" << EOF
# ArgoCD Project for ${GITLAB_GROUP}
# Auto-generated by init-project.sh

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${GITLAB_GROUP}
  namespace: argocd
spec:
  description: "GitOps POC project for ${GITLAB_GROUP}"

  sourceRepos:
    - 'https://d7561985.github.io/k8app'
    - 'https://${GITLAB_HOST}/${GITLAB_GROUP}/*'

  destinations:
    - namespace: '${NAMESPACE_PREFIX}-dev'
      server: https://kubernetes.default.svc
    - namespace: '${NAMESPACE_PREFIX}-staging'
      server: https://kubernetes.default.svc
    - namespace: '${NAMESPACE_PREFIX}-prod'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
EOF

echo_info "Updated: $PROJECT_FILE"

echo_header "Updating service configurations"

for SERVICE in $SERVICES; do
    SERVICE_DIR="$ROOT_DIR/services/$SERVICE"

    if [ ! -d "$SERVICE_DIR" ]; then
        echo_warn "Service directory not found: $SERVICE_DIR"
        continue
    fi

    # Update .gitlab-ci.yml
    CI_FILE="$SERVICE_DIR/.gitlab-ci.yml"
    if [ -f "$CI_FILE" ]; then
        sed -i.bak "s|gitops-poc/gitops-config|${GITLAB_GROUP}/gitops-config|g" "$CI_FILE"
        sed -i.bak "s|registry.gitlab.com/gitops-poc|registry.gitlab.com/${GITLAB_GROUP}|g" "$CI_FILE"
        rm -f "${CI_FILE}.bak"
        echo_info "Updated: $CI_FILE"
    fi

    # Update .cicd/default.yaml
    DEFAULT_FILE="$SERVICE_DIR/.cicd/default.yaml"
    if [ -f "$DEFAULT_FILE" ]; then
        sed -i.bak "s|gitops-poc|${GITLAB_GROUP}|g" "$DEFAULT_FILE"
        rm -f "${DEFAULT_FILE}.bak"
        echo_info "Updated: $DEFAULT_FILE"
    fi

    # Update vault-secret.yaml
    VAULT_FILE="$SERVICE_DIR/vault-secret.yaml"
    if [ -f "$VAULT_FILE" ]; then
        sed -i.bak "s|gitops-poc|${VAULT_PATH_PREFIX}|g" "$VAULT_FILE"
        rm -f "${VAULT_FILE}.bak"
        echo_info "Updated: $VAULT_FILE"
    fi
done

echo_header "Updating templates"

TEMPLATE_DIR="$ROOT_DIR/templates/service-repo"
if [ -d "$TEMPLATE_DIR" ]; then
    for FILE in "$TEMPLATE_DIR"/.gitlab-ci.yml "$TEMPLATE_DIR"/.cicd/*.yaml "$TEMPLATE_DIR"/vault-secret.yaml; do
        if [ -f "$FILE" ]; then
            sed -i.bak "s|gitops-poc|${GITLAB_GROUP}|g" "$FILE"
            rm -f "${FILE}.bak"
        fi
    done
    echo_info "Updated templates"
fi

echo_header "Updating Vault secrets script"

VAULT_SCRIPT="$ROOT_DIR/scripts/setup-vault-secrets.sh"
if [ -f "$VAULT_SCRIPT" ]; then
    sed -i.bak "s|gitops-poc|${VAULT_PATH_PREFIX}|g" "$VAULT_SCRIPT"
    rm -f "${VAULT_SCRIPT}.bak"
    echo_info "Updated: $VAULT_SCRIPT"
fi

echo ""
echo "========================================"
echo_info "Project initialization complete!"
echo "========================================"
echo ""
echo "Next steps:"
echo ""
echo "1. Create GitLab group: https://${GITLAB_HOST}/${GITLAB_GROUP}"
echo ""
echo "2. Create repositories:"
for SERVICE in $SERVICES; do
    echo "   - ${GITLAB_GROUP}/${SERVICE}"
done
echo "   - ${GITLAB_GROUP}/gitops-config"
echo ""
echo "3. Copy service files to their repos:"
for SERVICE in $SERVICES; do
    echo "   cp -r services/${SERVICE}/* /path/to/${SERVICE}/"
done
echo ""
echo "4. Run infrastructure setup (Vault, ArgoCD):"
echo "   ./scripts/setup-infrastructure.sh"
echo ""
echo "5. Create GitLab Deploy Token for Container Registry:"
echo "   - Go to: https://${GITLAB_HOST}/${GITLAB_GROUP}/-/settings/repository"
echo "   - Expand 'Deploy tokens' section"
echo "   - Create token with 'read_registry' scope"
echo "   - Add to .env:"
echo "       GITLAB_DEPLOY_TOKEN_USER='gitlab+deploy-token-xxxxx'"
echo "       GITLAB_DEPLOY_TOKEN='gldt-xxxxxxxxxxxx'"
echo ""
echo "6. Setup registry secrets (creates namespaces):"
echo "   ./scripts/setup-registry-secret.sh"
echo ""
echo "7. Configure Vault secrets:"
echo "   ./scripts/setup-vault-secrets.sh"
echo ""
