apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb
  namespace: infra-dev
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  namespaceSelector:
    matchNames:
      - infra-dev
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
