# =============================================================================
# Platform Modular Charts - ArgoCD Applications (Layer 4)
# =============================================================================
# ArgoCD manages ONLY Layer 4 - Applications.
# Infrastructure (Layer 0-3) is managed by scripts, NOT ArgoCD.
#
# Architecture:
#   Layer 0-3: Infrastructure (setup-infrastructure.sh)
#   Layer 4: Applications (ArgoCD - this file)
#
# Applications (sync order):
# - platform-core: Namespaces, Gateway, ApplicationSet, Vault (sync-wave: -10)
# - service-groups: Infrastructure access routes (sync-wave: -5)
# - preview-environments: Feature branch previews (sync-wave: -4)
# - ingress-cloudflare: CloudFlare Tunnel routing (sync-wave: -3)
#
# Values structure (multi-source):
# - base.yaml: Shared settings (global, dns, ingress, vault, environments)
# - {chart}.yaml: Chart-specific configuration
# =============================================================================

---
# =============================================================================
# Platform Core - Namespaces, Gateway, ApplicationSet, Vault
# =============================================================================
# Foundation layer that creates:
# - Environment namespaces (poc-dev, etc.)
# - Gateway per environment
# - ApplicationSet for services
# - VaultAuth resources
# - Bootstrap job for Vault policies
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-poc-dzha

  sources:
    - repoURL: https://gitlab.com/gitops-poc-dzha/infra/poc/gitops-config.git
      targetRevision: main
      ref: values
    - repoURL: https://gitlab.com/gitops-poc-dzha/infra/poc/gitops-config.git
      targetRevision: main
      path: charts/platform-core
      helm:
        valueFiles:
          - $values/platform/base.yaml
          - $values/platform/core.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
# =============================================================================
# Service Groups - Infrastructure External Access
# =============================================================================
# Provides external access to: ArgoCD, Grafana, Vault, Hubble
# Creates: Namespace, Gateway, HTTPRoutes, ReferenceGrants
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-service-groups
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-poc-dzha

  sources:
    # Values source
    - repoURL: https://gitlab.com/gitops-poc-dzha/infra/poc/gitops-config.git
      targetRevision: main
      ref: values
    # Chart source with multi-source values
    - repoURL: https://gitlab.com/gitops-poc-dzha/infra/poc/gitops-config.git
      targetRevision: main
      path: charts/service-groups
      helm:
        valueFiles:
          - $values/platform/base.yaml
          - $values/platform/service-groups.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
# =============================================================================
# Preview Environments - Feature Branch Deployments
# =============================================================================
# Automatic preview environments for GitLab Merge Requests.
# Creates: ApplicationSet with Pull Request Generator
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-preview-envs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-poc-dzha

  sources:
    - repoURL: https://gitlab.com/gitops-poc-dzha/infra/poc/gitops-config.git
      targetRevision: main
      ref: values
    - repoURL: https://gitlab.com/gitops-poc-dzha/infra/poc/gitops-config.git
      targetRevision: main
      path: charts/preview-environments
      helm:
        valueFiles:
          - $values/platform/base.yaml
          - $values/platform/preview.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
# =============================================================================
# Ingress CloudFlare - Tunnel Routing Aggregation
# =============================================================================
# CloudFlare Tunnel deployment with aggregated routing.
# Creates: Namespace, ConfigMap, Deployment
# Aggregates routes from: environments, service-groups, preview-envs
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-poc-dzha

  sources:
    - repoURL: https://gitlab.com/gitops-poc-dzha/infra/poc/gitops-config.git
      targetRevision: main
      ref: values
    - repoURL: https://gitlab.com/gitops-poc-dzha/infra/poc/gitops-config.git
      targetRevision: main
      path: charts/ingress-cloudflare
      helm:
        valueFiles:
          - $values/platform/base.yaml
          - $values/platform/service-groups.yaml
          - $values/platform/ingress.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
