# GitLab Repository Credentials for ArgoCD
# This provides credentials for ALL repos under gitops-poc-dzha group
#
# IMPORTANT: This file is a TEMPLATE. Apply it with your token:
#   export GITLAB_TOKEN="your-token-here"
#   envsubst < repo-credentials.yaml | kubectl apply -f -
#
# Or create the secret manually:
#   kubectl create secret generic gitlab-repo-creds -n argocd \
#     --from-literal=type=git \
#     --from-literal=url=https://gitlab.com/gitops-poc-dzha \
#     --from-literal=username=oauth2 \
#     --from-literal=password=${GITLAB_TOKEN}
#   kubectl label secret gitlab-repo-creds -n argocd argocd.argoproj.io/secret-type=repo-creds

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://gitlab.com/gitops-poc-dzha
  username: oauth2
  password: ${GITLAB_TOKEN}
