{{- /*
HTTPRoute Template for k8app Helm Chart
======================================

This template creates a Gateway API HTTPRoute resource.
Add this file to: charts/app/templates/httproute.yaml

Required Gateway API CRDs must be installed in the cluster.
*/ -}}

{{- if .Values.httpRoute }}
{{- if .Values.httpRoute.enabled }}
{{- $serviceName := include "name" . }}
{{- $servicePort := .Values.service.ports | first | default dict }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $serviceName }}-route
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $serviceName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    {{- if .Values.httpRoute.primaryHost }}
    app.kubernetes.io/primary-host: {{ .Values.httpRoute.primaryHost | quote }}
    {{- end }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- /* Parent Gateway references */ -}}
  parentRefs:
    {{- range .Values.httpRoute.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
    {{- end }}

  {{- /* Hostnames */ -}}
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}

  {{- /* Routing rules */ -}}
  rules:
    {{- if .Values.httpRoute.rules }}
    {{- range .Values.httpRoute.rules }}
    - matches:
        {{- range .matches }}
        - {{- if .path }}
          path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value | quote }}
          {{- end }}
          {{- if .headers }}
          headers:
            {{- range .headers }}
            - name: {{ .name }}
              value: {{ .value | quote }}
              {{- if .type }}
              type: {{ .type }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .method }}
          method: {{ .method }}
          {{- end }}
        {{- end }}
      {{- if .backendRefs }}
      backendRefs:
        {{- range .backendRefs }}
        - name: {{ .name | default (printf "%s-sv" $serviceName) }}
          port: {{ .port | default ($servicePort.externalPort | default 80) }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
          {{- if .weight }}
          weight: {{ .weight }}
          {{- end }}
        {{- end }}
      {{- else }}
      {{- /* Default: route to this service */ -}}
      backendRefs:
        - name: {{ $serviceName }}-sv
          port: {{ $servicePort.externalPort | default 80 }}
      {{- end }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- else }}
    {{- /* Default rule: route all traffic to this service */ -}}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $serviceName }}-sv
          port: {{ $servicePort.externalPort | default 80 }}
    {{- end }}
{{- end }}
{{- end }}
