# Health Demo Service - Default Values
# gRPC health check and streaming demo service
# Inherits: serviceAccountName, imagePullSecrets, secretsProvider, serviceMonitor
# from platform shared/k8app-defaults.yaml

appName: health-demo
version: "1.0.0"

image:
  repository: health-demo
  tag: local
  pullPolicy: Never

service:
  enabled: true
  type: ClusterIP
  ports:
    grpc:
      externalPort: 8081
      internalPort: 8081
      protocol: TCP
    metrics:
      externalPort: 9090
      internalPort: 9090
      protocol: TCP

livenessProbe:
  enabled: true
  mode: tcpSocket
  tcpSocket:
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: tcpSocket
  tcpSocket:
    port: 8081
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

args:
  - "-port=8081"
  - "-metrics-port=9090"

# Service-specific secrets (paths only, provider inherited)
secrets:
  ENVIRONMENT: "/gitops-poc-dzha/health-demo/dev/config"
  SERVICE_NAME: "/gitops-poc-dzha/health-demo/dev/config"
