# Health Demo Service - Default Values
# gRPC health check and streaming demo service
# Implements grpc.health.v1.Health with Check and Watch methods
# Based on k8app/app chart: https://github.com/d7561985/k8app

appName: health-demo
version: "1.0.0"

serviceAccountName: health-demo

# Image configuration
# For local Minikube: repository: health-demo, tag: local, pullPolicy: Never
# For GitLab Registry: repository: registry.gitlab.com/${GITLAB_GROUP}/health-demo
image:
  repository: health-demo
  tag: local
  pullPolicy: Never  # Change to IfNotPresent for GitLab Registry

# Service configuration (k8app format)
service:
  enabled: true
  type: ClusterIP
  ports:
    grpc:
      externalPort: 8081
      internalPort: 8081
      protocol: TCP

# Health checks - gRPC tcpSocket fallback (k8app format)
livenessProbe:
  enabled: true
  mode: tcpSocket
  tcpSocket:
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: tcpSocket
  tcpSocket:
    port: 8081
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

# Command line args passed to the binary
args:
  - "-port=8081"
