# Health Demo Service - Default Values
# gRPC health check and streaming demo

appName: health-demo
version: "1.0.0"

serviceAccountName: health-demo

# Image configuration
# For local Minikube: repository: health-demo, tag: local, pullPolicy: Never
# For GitLab Registry: repository: registry.gitlab.com/${GITLAB_GROUP}/health-demo
image:
  repository: health-demo
  tag: local
  pullPolicy: Never  # Change to IfNotPresent for GitLab Registry

# Enable imagePullSecrets for GitLab Container Registry
# k8app chart uses hardcoded secret name "regsecret"
# Run: ./scripts/setup-registry-secret.sh to create the secret
deploySecretHarbor: false  # Set to true when using GitLab Registry

containerPort: 8081

service:
  enabled: true
  type: ClusterIP
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081

livenessProbe:
  enabled: true
  grpc:
    port: 8081
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: true
  grpc:
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 5

env:
  - name: PORT
    value: "8081"

labels:
  app.kubernetes.io/name: health-demo
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: gitops-poc-dzha-dzha
  app.kubernetes.io/managed-by: helm
