# Health Demo - Production Environment
# Inherits from default.yaml
# CI updates image.repository and image.tag on each build

environment: prod
branch: main

# Image - CI updates these values
image:
  repository: registry.gitlab.com/gitops-poc-dzha/services/health-demo
  tag: latest
  pullPolicy: IfNotPresent

replicas: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

labels:
  app.kubernetes.io/instance: health-demo-prod
  environment: prod

annotations:
  argocd.argoproj.io/sync-wave: "0"

pdb:
  enabled: true
  minAvailable: 1
