# Health Demo - Production Environment

environment: prod
branch: main
replicas: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

labels:
  app.kubernetes.io/instance: health-demo-prod
  environment: prod

annotations:
  argocd.argoproj.io/sync-wave: "0"

pdb:
  enabled: true
  minAvailable: 1
