# Health Demo - Staging Environment
# Inherits from default.yaml
# CI updates image.repository and image.tag on each build

environment: staging
branch: main

# Image - CI updates these values
image:
  repository: registry.gitlab.com/gitops-poc-dzha/health-demo
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

labels:
  app.kubernetes.io/instance: health-demo-staging
  environment: staging

annotations:
  argocd.argoproj.io/sync-wave: "0"
