apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  # Monitor services in same namespace (set by ArgoCD destination)
  namespaceSelector:
    matchNames: []
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
