# k8app configuration for wager-service (bonus service)
# PHP/Symfony bonus and wager management

appName: sentry-wager

serviceAccountName: default

image:
  repository: registry.gitlab.com/gitops-poc-dzha/services/sentry-demo/wager-service
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: regsecret

# Service configuration (k8app format)
service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      externalPort: 8085
      internalPort: 8085
      protocol: TCP

# Health checks
livenessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8085
    path: "/health"
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  mode: httpGet
  httpGet:
    port: 8085
    path: "/health"
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Environment via configmap (environment-agnostic)
configmap:
  APP_ENV: prod
  APP_VERSION: "1.0.0"
  MONGODB_DB: wager
  # Sentry configuration (DSN is universal, environment in overlay)
  SENTRY_DSN: "https://5ee8fdaf0f6792fa532ddfdf657787e4@o4509616118562816.ingest.de.sentry.io/4509626097270864"
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  # Service-to-service (same namespace = short DNS)
  USER_SERVICE_URL: "http://sentry-user-sv:8081"
  PAYMENT_SERVICE_URL: "http://sentry-payment-sv:8083"
  # MONGODB_URL, SENTRY_ENVIRONMENT → defined in env overlay

# =============================================================================
# Prometheus ServiceMonitor (k8app v3.8.0+)
# =============================================================================
serviceMonitor:
  enabled: true
  port: "http"
  path: "/metrics"
  interval: 30s

# Vault secrets integration (role/path in env overlay)
vault:
  enabled: true
